- Includes:
    - ./rpfs/**/*.rpf
  CompileTargets:
    - Input: ./rpfs/FormatterBenchmarks/FormatterBenchmarks.Internal.rpf
      Output: ./perf/FormatterBenchmarks/Internal/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Core.Cryptography/Omnius.Core.Cryptography.rpf
      Output: ./src/Omnius.Core.Cryptography/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Core.Network/Omnius.Core.Network.rpf
      Output: ./src/Omnius.Core.Network/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Core.Network/Omnius.Core.Network.Connections.Secure.rpf
      Output: ./src/Omnius.Core.Network/Connections/Secure/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Core.Network/Omnius.Core.Network.Connections.Secure.Internal.rpf
      Output: ./src/Omnius.Core.Network/Connections/Secure/Internal/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Core.Network/Omnius.Core.Network.Connections.Secure.V1.Internal.rpf
      Output: ./src/Omnius.Core.Network/Connections/Secure/V1/Internal/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Core.RocketPack.Remoting/Omnius.Core.RocketPack.Remoting.rpf
      Output: ./src/Omnius.Core.RocketPack.Remoting/_RocketPack/_Generated.cs
- Includes:
  CompileTargets:
    - Input: ./rpfs/Omnius.Core.RocketPack.Tests/Omnius.Core.RocketPack.Tests.Internal.rpf
      Output: ./test/Omnius.Core.RocketPack.Tests/Internal/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Core.RocketPack.Remoting.Tests/Omnius.Core.RocketPack.Remoting.Tests.Internal.rpf
      Output: ./test/Omnius.Core.RocketPack.Remoting.Tests/Internal/_RocketPack/_Generated.cs
