name: Submodules Sync Notify

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  notify:
    name: Submodules Sync Notify
    runs-on: ubuntu-latest

    steps:
    - name: Github REST API Call
      env:
        CI_TOKEN: ${{ secrets.PAT }}
        PARENT_REPO: omnius-labs/xeus
      run: |
          curl -vv -H "Authorization: token ${{ secrets.CI_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${{ PARENT_REPO }}/dispatches" -d '{"event_type": "update"}'
