name: update

on:
  schedule:
    - cron: "* 12 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
      - name: security update
        run: make update
      - name: create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          title: Security Update into develop.
          branch: security-fix
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: slack notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: "#3278BD"
          #SLACK_ICON:
          SLACK_MESSAGE: "Security Update into develop"
          SLACK_TITLE: GitHub Action
          SLACK_USERNAME: GitHub Action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
